<a href="https://colab.research.google.com/github/Kavi-Sarna/365-python/blob/main/7%20-%20Data%20Preprocessing%20with%20NumPy/7%20-%20Statistics%20with%20NumPy/1%20-%20Using%20Statistical%20Functions%20in%20NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
matrix_A = np.array([ [ 1, 0, 0, 3, 1 ], [ 3, 6, 6, 2, 9 ], [ 4, 5, 3, 8, 0 ] ])
matrix_A

array([[1, 0, 0, 3, 1],
       [3, 6, 6, 2, 9],
       [4, 5, 3, 8, 0]])

In [4]:
np.mean(matrix_A)

3.4

In [5]:
np.mean(matrix_A[0])

1.0

In [6]:
np.mean(matrix_A[:, 0])

2.6666666666666665

In [7]:
np.mean(matrix_A, axis = 0)

array([2.66666667, 3.66666667, 3.        , 4.33333333, 3.33333333])

In [8]:
np.mean(matrix_A, axis = 1)

array([1. , 5.2, 4. ])

In [9]:
matrix_A.mean()

3.4

In [10]:
np.sqrt(matrix_A)

array([[1.        , 0.        , 0.        , 1.73205081, 1.        ],
       [1.73205081, 2.44948974, 2.44948974, 1.41421356, 3.        ],
       [2.        , 2.23606798, 1.73205081, 2.82842712, 0.        ]])

In [11]:
matrix_A.sqrt()

AttributeError: ignored

In [12]:
np.mean(matrix_A, axis = 1, dtype = np.int64)

array([1, 5, 4])