<a href="https://colab.research.google.com/github/Kavi-Sarna/365-python/blob/main/7%20-%20Data%20Preprocessing%20with%20NumPy/7%20-%20Statistics%20with%20NumPy/2%20-%20Minimal%20and%20Maximal%20Values%20in%20NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
matrix_A = np.array([ [ 1, 0, 0, 3, 1 ], [ 3, 6, 6, 2, 9 ], [ 4, 5, 3, 8, 0 ] ])
matrix_A

array([[1, 0, 0, 3, 1],
       [3, 6, 6, 2, 9],
       [4, 5, 3, 8, 0]])

In [5]:
np.min(matrix_A)

0

In [6]:
np.min(matrix_A[1])

2

In [4]:
np.amin(matrix_A)

0

In [9]:
np.minimum(matrix_A[0], matrix_A[2])

array([1, 0, 0, 3, 0])

In [10]:
np.minimum(matrix_A[1], matrix_A[2])

array([3, 5, 3, 2, 0])

In [11]:
np.minimum.reduce(matrix_A)

array([1, 0, 0, 2, 0])

In [12]:
np.min(matrix_A, axis = 0)

array([1, 0, 0, 2, 0])

In [13]:
np.min(matrix_A, axis = 1)

array([0, 2, 0])

In [14]:
np.max(matrix_A)

9

In [15]:
np.amax(matrix_A)

9

In [17]:
np.maximum.reduce(matrix_A)

array([4, 6, 6, 8, 9])