<a href="https://colab.research.google.com/github/Kavi-Sarna/365-python/blob/main/7%20-%20Data%20Preprocessing%20with%20NumPy/7%20-%20Statistics%20with%20NumPy/3%20-%20Statistical%20Order%20Functions%20in%20NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
matrix_A = np.array([ [ 1, 0, 0, 3, 1 ], [ 3, 6, 6, 2, 9 ], [ 4, 5, 3, 8, 0 ] ])
matrix_A

array([[1, 0, 0, 3, 1],
       [3, 6, 6, 2, 9],
       [4, 5, 3, 8, 0]])

In [3]:
np.ptp(matrix_A)

9

In [4]:
np.ptp(matrix_A, axis = 0)

array([3, 6, 6, 6, 9])

In [5]:
np.ptp(matrix_A, axis = 1)

array([3, 7, 8])

In [6]:
np.sort(matrix_A, axis = None)

array([0, 0, 0, 1, 1, 2, 3, 3, 3, 4, 5, 6, 6, 8, 9])

In [7]:
np.percentile(matrix_A, 70)

4.799999999999999

In [8]:
np.percentile(matrix_A, 70, interpolation = 'midpoint')

<ipython-input-8-b6612268da06>:1: DeprecationWarning: the `interpolation=` argument to percentile was renamed to `method=`, which has additional options.
Users of the modes 'nearest', 'lower', 'higher', or 'midpoint' are encouraged to review the method they used. (Deprecated NumPy 1.22)
  np.percentile(matrix_A, 70, interpolation = 'midpoint')


4.5

In [9]:
np.percentile(matrix_A, 70, method = 'midpoint')

4.5

In [10]:
np.percentile(matrix_A, 70, method = 'higher')

5

In [11]:
np.percentile(matrix_A, 70, method = 'lower')

4

In [12]:
np.percentile(matrix_A, 70, method = 'nearest')

5

In [13]:
type(np.percentile(matrix_A, 70, method = 'nearest'))

numpy.int64

In [14]:
type(np.percentile(matrix_A, 70))

numpy.float64

In [15]:
np.percentile(matrix_A, 50)

3.0

In [16]:
np.percentile(matrix_A, 0)

0.0

In [17]:
np.percentile(matrix_A, 100)

9.0

In [18]:
np.quantile(matrix_A, 0.7)

4.799999999999999

In [19]:
np.quantile(matrix_A, 0.7, method = 'nearest')

5