<a href="https://colab.research.google.com/github/Kavi-Sarna/365-python/blob/main/7%20-%20Data%20Preprocessing%20with%20NumPy/7%20-%20Statistics%20with%20NumPy/5%20-%20Covariance%20and%20Correlation%20in%20NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
matrix_A = np.array([ [ 1, 0, 0, 3, 1 ], [ 3, 6, 6, 2, 9 ], [ 4, 5, 3, 8, 0 ] ])
matrix_A

array([[1, 0, 0, 3, 1],
       [3, 6, 6, 2, 9],
       [4, 5, 3, 8, 0]])

In [3]:
np.cov(matrix_A)

array([[ 1.5, -2. ,  2. ],
       [-2. ,  7.7, -7. ],
       [ 2. , -7. ,  8.5]])

In [4]:
np.corrcoef(matrix_A)

array([[ 1.        , -0.58848989,  0.56011203],
       [-0.58848989,  1.        , -0.8652532 ],
       [ 0.56011203, -0.8652532 ,  1.        ]])