<a href="https://colab.research.google.com/github/Kavi-Sarna/365-python/blob/main/7%20-%20Data%20Preprocessing%20with%20NumPy/1%20-%20Introduction%20to%20NumPy/1%20-%20NumPy%20array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
np.__version__

'1.26.2'

In [3]:
array_a = np.array([1, 2, 3])

In [4]:
array_a

array([1, 2, 3])

In [5]:
array_b = np.array([[1, 2, 3], [4, 5, 6]])
array_b

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
np.mean(array_b)

3.5

In [7]:
np.mean(array_b, axis=0)

array([2.5, 3.5, 4.5])