<a href="https://colab.research.google.com/github/Kavi-Sarna/365-python/blob/main/4%20-%20Data%20Cleaning%20and%20Preprocessing%20with%20pandas/2%20-%20pandas%20Series/2%20-%20Converting%20Series%20into%20Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np

In [3]:
prices_per_category = pd.Series({ 'Product A': 22250, 'Product B': 16600, 'Product C': 15600 })
prices_per_category

Product A    22250
Product B    16600
Product C    15600
dtype: int64

In [4]:
prices_per_category.values

array([22250, 16600, 15600])

In [5]:
type(prices_per_category.values)

numpy.ndarray

In [6]:
prices_per_category.array

<PandasArray>
[22250, 16600, 15600]
Length: 3, dtype: int64

In [7]:
type(prices_per_category.array)

pandas.core.arrays.numpy_.PandasArray

In [8]:
prices_per_category.to_numpy()

array([22250, 16600, 15600])

In [9]:
type(prices_per_category.to_numpy())

numpy.ndarray

In [10]:
test_array = prices_per_category[['Product A', 'Product B']].to_numpy(dtype='float')
test_array

array([22250., 16600.])

In [11]:
type(test_array[0])

numpy.float64

In [12]:
prices_per_category.values[0]

22250

In [13]:
type(prices_per_category.values[0])

numpy.int64

In [14]:
prices_per_category.array[0]

22250

In [15]:
type(prices_per_category.array[0])

numpy.int64

In [16]:
prices_per_category.to_numpy()[0]

22250

In [17]:
type(prices_per_category.to_numpy()[0])

numpy.int64