<a href="https://colab.research.google.com/github/Kavi-Sarna/365-python/blob/main/7%20-%20Data%20Preprocessing%20with%20NumPy/2%20-%20Why%20use%20NumPy/1%20-%20Ndarrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
array_a = np.array([1, 2, 3])
array_a

array([1, 2, 3])

In [4]:
type(array_a)

numpy.ndarray

In [5]:
print(array_a)

[1 2 3]


In [6]:
array_a.shape

(3,)

In [7]:
array_b = np.array([ [ 1, 2, 3 ], [ 4, 5, 6 ] ])
array_b

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
type(array_b)

numpy.ndarray

In [9]:
print(array_b)

[[1 2 3]
 [4 5 6]]


In [10]:
array_b.shape

(2, 3)

In [11]:
array_b.shape[0]

2

In [12]:
array_b.shape[1]

3

In [13]:
array_c = np.array(13)
array_c

array(13)

In [14]:
type(array_c)

numpy.ndarray

In [15]:
print(array_c)

13


In [16]:
array_c.shape

()

In [17]:
array_d = np.array([15])
array_d

array([15])

In [18]:
type(array_d)

numpy.ndarray

In [19]:
print(array_d)

[15]


In [20]:
array_d.shape

(1,)

In [21]:
array_e = np.array([[15]])
array_e

array([[15]])

In [22]:
type(array_e)

numpy.ndarray

In [23]:
print(array_e)

[[15]]


In [24]:
array_e.shape

(1, 1)