<a href="https://colab.research.google.com/github/Kavi-Sarna/365-python/blob/main/7%20-%20Data%20Preprocessing%20with%20NumPy/2%20-%20Why%20use%20NumPy/2%20-%20Arrays%20vs%20Lists.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [6]:
list_a = [1, 2, 3, 4, 5, 6]
list_a

[1, 2, 3, 4, 5, 6]

In [3]:
len(list_a)

6

In [7]:
list_b  = [ [1, 2, 3], [4, 5, 6]]
list_b

[[1, 2, 3], [4, 5, 6]]

In [5]:
len(list_b)

2

In [8]:
array_a = np.array(list_b)
array_a

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
type(list_b)

list

In [10]:
type(array_a)

numpy.ndarray

In [11]:
print(list_b)

[[1, 2, 3], [4, 5, 6]]


In [12]:
print(array_a)

[[1 2 3]
 [4 5 6]]


In [13]:
array_a.shape

(2, 3)

In [14]:
list_b.shape

AttributeError: ignored

In [15]:
len(list_b)

2

In [16]:
len(list_b[0])

3

In [17]:
len(list_b[1])

3

In [18]:
list_b

[[1, 2, 3], [4, 5, 6]]

In [19]:
array_a

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
list_c = list_b[0] + list_b[1]
array_b = array_a[0] + array_a[1]

In [21]:
print(list_c)

[1, 2, 3, 4, 5, 6]


In [22]:
print(array_b)

[5 7 9]


In [23]:
import math
array_c = math.sqrt(list_a[1, 0])
print(array_c)

TypeError: ignored

In [25]:
array_c = math.sqrt(array_a[1, 0])
print(array_c)

2.0


In [26]:
np.sqrt(array_a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])