<a href="https://colab.research.google.com/github/Kavi-Sarna/365-python/blob/main/7%20-%20Data%20Preprocessing%20with%20NumPy/5%20-%20Generating%20Data%20with%20NumPy/1%20-%20Arrays%20of%200s%20and%201s.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
array_empty = np.empty(shape = (2, 3))
array_empty

array([[4.84185568e-310, 0.00000000e+000, 2.05833592e-312],
       [6.79038654e-313, 2.14321575e-312, 2.27053550e-312]])

In [4]:
array_0s = np.zeros(shape = (2, 3))
array_0s

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
array_0s = np.zeros(shape = (2, 3), dtype = np.int8)
array_0s

array([[0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [6]:
array_1s = np.ones(shape = (2, 3))
array_1s

array([[1., 1., 1.],
       [1., 1., 1.]])

In [7]:
array_full = np.full(shape = (2, 3))
array_full

TypeError: ignored

In [8]:
array_full = np.full(shape = (2, 3), fill_value = 2)
array_full

array([[2, 2, 2],
       [2, 2, 2]])

In [9]:
array_full = np.full(shape = (2, 3), fill_value = 'Three-Six-Five')
array_full

array([['Three-Six-Five', 'Three-Six-Five', 'Three-Six-Five'],
       ['Three-Six-Five', 'Three-Six-Five', 'Three-Six-Five']],
      dtype='<U14')