<a href="https://colab.research.google.com/github/Kavi-Sarna/365-python/blob/main/7%20-%20Data%20Preprocessing%20with%20NumPy/5%20-%20Generating%20Data%20with%20NumPy/2%20-%20%22_like%22%20functions%20in%20NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
matrix_A = np.array([ [ 1, 0, 9, 2, 2 ], [ 3, 23, 4, 5, 1 ], [ 0, 2, 3, 4, 1 ] ])
matrix_A

array([[ 1,  0,  9,  2,  2],
       [ 3, 23,  4,  5,  1],
       [ 0,  2,  3,  4,  1]])

In [5]:
array_empty_like = np.empty_like(matrix_A)
array_empty_like

array([[    101171563585757,                   0,                   0,
                          0, 7953764122015825920],
       [8319683848551211643, 3180222411935070754, 8391722768137527840,
        7959390389040738153, 2459013998934893172],
       [8104338990068757365, 8317708060499076466, 2459014313992534562,
        2478212826149773680,                 128]])

In [6]:
array_0s_like = np.zeros_like(matrix_A)
array_0s_like

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [7]:
array_1s_like = np.ones_like(matrix_A)
array_1s_like

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [9]:
array_full_like = np.full_like(matrix_A, fill_value = 2)
array_full_like

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])