<a href="https://colab.research.google.com/github/Kavi-Sarna/365-python/blob/main/7%20-%20Data%20Preprocessing%20with%20NumPy/5%20-%20Generating%20Data%20with%20NumPy/4%20-%20Random%20Generators%20and%20Seeds.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
from numpy.random import Generator as gen
from numpy.random import PCG64 as pcg

In [3]:
array_RG = gen(pcg())
array_RG

Generator(PCG64) at 0x7A6CF0407A00

In [4]:
array_RG.normal()

0.7012565085543303

In [5]:
array_RG.normal(size = 5)

array([-1.37712838, -0.88668642, -0.71849673, -0.3967052 ,  0.24848124])

In [6]:
array_RG.normal(size = (5, 5))

array([[ 1.24135768,  1.39761134, -0.58911195, -1.13668311,  0.94668176],
       [-0.07060214, -1.01061468,  1.5661254 , -0.78818442, -0.3664216 ],
       [ 0.48011906,  0.19357953,  0.13473709,  0.99967557, -0.45630312],
       [ 0.73596769,  0.04805788,  0.81392918,  1.29248181, -0.14981643],
       [ 0.21900755, -0.36028768, -1.78438884,  1.92017641,  1.29700843]])

In [9]:
array_RG = gen(pcg(seed = 365))
array_RG.normal(size = (5, 5))

array([[-0.13640899,  0.09414431, -0.06300442,  1.05391641, -0.6866818 ],
       [-0.50922173, -0.7999526 ,  0.73041825,  0.08825439, -2.1177576 ],
       [ 0.65526774, -0.48095012, -0.5519114 , -0.58578662, -0.98257896],
       [ 1.12378166, -1.30984316, -0.04703774,  0.955272  ,  0.26071745],
       [-0.20023668, -1.50172484, -1.4929163 ,  0.96535084,  1.18694633]])

In [10]:
array_RG.normal(size = (5, 5))

array([[-0.76065577,  1.48158358,  0.01200258, -0.06846959,  0.25301664],
       [-0.52640788,  0.79613109,  0.28203421,  1.80238008,  0.93932117],
       [-0.53693283, -0.26317689, -1.77723035,  1.14900013, -2.20733915],
       [ 1.54116775, -0.5124932 , -2.14564563,  1.98878673,  0.32208907],
       [-1.2651495 ,  3.2714633 ,  1.78650493, -0.20233675,  0.20427467]])