<a href="https://colab.research.google.com/github/Kavi-Sarna/365-python/blob/main/7%20-%20Data%20Preprocessing%20with%20NumPy/5%20-%20Generating%20Data%20with%20NumPy/5%20-%20Basic%20Random%20Functions%20in%20NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
from numpy.random import Generator as gen
from numpy.random import PCG64 as pcg

In [3]:
array_RG = gen(pcg(seed = 365))
array_RG.integers(10, size = (5, 5))

array([[0, 7, 6, 7, 8],
       [6, 6, 2, 0, 6],
       [3, 0, 3, 7, 9],
       [1, 1, 8, 7, 4],
       [4, 8, 6, 4, 9]])

In [4]:
array_RG = gen(pcg(seed = 365))
array_RG.integers(low = 10, high = 100, size = (5, 5))

array([[18, 78, 64, 78, 84],
       [66, 67, 28, 10, 69],
       [45, 15, 37, 74, 96],
       [19, 21, 89, 73, 54],
       [53, 84, 66, 51, 92]])

In [5]:
array_RG = gen(pcg(seed = 365))
array_RG.random(size = (5, 5))

array([[0.75915734, 0.7662218 , 0.6291028 , 0.20336599, 0.66501486],
       [0.06559111, 0.71326309, 0.10812106, 0.87969046, 0.49405844],
       [0.82472673, 0.45652944, 0.07367232, 0.69628564, 0.36690736],
       [0.29787156, 0.4996155 , 0.4865245 , 0.62740703, 0.54952637],
       [0.64894629, 0.04411757, 0.7206516 , 0.84594003, 0.17159792]])

In [6]:
array_RG = gen(pcg(seed = 365))
array_RG.choice([1, 2, 3, 4, 5], size = (5, 5))

array([[1, 4, 4, 4, 5],
       [4, 4, 2, 1, 4],
       [2, 1, 2, 4, 5],
       [1, 1, 5, 4, 3],
       [3, 5, 4, 3, 5]])

In [8]:
array_RG = gen(pcg(seed = 365))
array_RG.choice([1, 2, 3, 4, 5], p = [ 0.1, 0.1, 0.1, 0.1, 0.6 ], size = (5, 5))

array([[5, 5, 5, 3, 5],
       [1, 5, 2, 5, 5],
       [5, 5, 1, 5, 4],
       [3, 5, 5, 5, 5],
       [5, 1, 5, 5, 2]])