<a href="https://colab.research.google.com/github/Kavi-Sarna/365-python/blob/main/7%20-%20Data%20Preprocessing%20with%20NumPy/3%20-%20NumPy%20Fundamentals/1%20-%20Indexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
array_a = np.array([ [ 1, 2, 3 ], [ 4, 5, 6 ] ])
array_a

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
array_a[0]

array([1, 2, 3])

In [4]:
array_a[1]

array([4, 5, 6])

In [5]:
array_a[2]

IndexError: ignored

In [6]:
array_a[0][1]

2

In [7]:
array_a[1][0]

4

In [8]:
array_a[1, 0]

4

In [9]:
array_a[0, 1]

2

In [10]:
array_a[:, 0]

array([1, 4])

In [11]:
array_b = np.array([1, 2, 3])
array_b[-1]

3

In [12]:
array_a

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
array_a[-1]

array([4, 5, 6])

In [14]:
array_a[:, -1]

array([3, 6])

In [15]:
array_a[-1, -1]

6

In [16]:
array_a[-3]

IndexError: ignored