<a href="https://colab.research.google.com/github/Kavi-Sarna/365-python/blob/main/7%20-%20Data%20Preprocessing%20with%20NumPy/3%20-%20NumPy%20Fundamentals/2%20-%20Assigning%20Values.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
array_a = np.array([ [ 1, 2, 3 ], [ 4, 5, 6 ] ])
array_a

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
array_a[0, 2] = 9

In [4]:
array_a

array([[1, 2, 9],
       [4, 5, 6]])

In [8]:
array_a[0] = 9
array_a

array([[9, 9, 9],
       [9, 5, 6]])

In [7]:
array_a[:, 0] = 9
array_a

array([[9, 9, 9],
       [9, 5, 6]])

In [9]:
list_a = [8, 7, 8]

array_a[0] = list_a
array_a

array([[8, 7, 8],
       [9, 5, 6]])

In [10]:
type(array_a)

numpy.ndarray

In [11]:
type(array_a[0])

numpy.ndarray

In [12]:
array_a[:] = 9
array_a

array([[9, 9, 9],
       [9, 9, 9]])

In [13]:
array_a = 9
array_a

9

In [14]:
type(array_a)

int

In [15]:
array_a = np.array([ [ 1, 2, 3 ], [ 4, 5, 6 ] ])
array_a

array([[1, 2, 3],
       [4, 5, 6]])