<a href="https://colab.research.google.com/github/Kavi-Sarna/365-python/blob/main/7%20-%20Data%20Preprocessing%20with%20NumPy/3%20-%20NumPy%20Fundamentals/3%20-%20Elementwise%20properties.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
array_a = np.array([7, 8, 9])
array_a

array([7, 8, 9])

In [3]:
array_b = np.array([ [ 1, 2, 3 ], [ 4, 5, 6 ] ])
array_b

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
array_a + 2

array([ 9, 10, 11])

In [5]:
array_b + 2

array([[3, 4, 5],
       [6, 7, 8]])

In [6]:
array_b - 2

array([[-1,  0,  1],
       [ 2,  3,  4]])

In [7]:
array_b * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [8]:
list_a = [ 1, 2, 3]
list_a + [2]

[1, 2, 3, 2]

In [9]:
array_a

array([7, 8, 9])

In [10]:
array_a + 2

array([ 9, 10, 11])

In [11]:
array_a + array_b[0]

array([ 8, 10, 12])

In [12]:
array_a + array_a[1]

array([15, 16, 17])

In [13]:
array_a - array_b[1]

array([3, 3, 3])

In [14]:
array_a * array_b[1]

array([28, 40, 54])

In [15]:
array_a + array_b

array([[ 8, 10, 12],
       [11, 13, 15]])

In [16]:
array_a * array_b

array([[ 7, 16, 27],
       [28, 40, 54]])

In [17]:
array_a - array_b

array([[6, 6, 6],
       [3, 3, 3]])

In [18]:
array_b - array_a

array([[-6, -6, -6],
       [-3, -3, -3]])