<a href="https://colab.research.google.com/github/Kavi-Sarna/365-python/blob/main/7%20-%20Data%20Preprocessing%20with%20NumPy/3%20-%20NumPy%20Fundamentals/4%20-%20Types%20of%20Data%20Supported.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
array_a = np.array([ [ 1, 2, 3 ], [ 4, 5, 6 ] ])
array_a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
array_a = np.array([ [ 1, 2, 3 ], [ 4, 5, 6 ] ], dtype = 'float32')
array_a

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [5]:
array_a = np.array([ [ 1, 2, 3 ], [ 4, 5, 6 ] ], dtype = np.float16)
array_a

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float16)

In [6]:
array_a = np.array([ [ 1, 2, 3 ], [ 4, 5, 6 ] ], dtype = np.complex64)
array_a

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]], dtype=complex64)

In [8]:
array_a = np.array([ [ 1, 2, 3 ], [ 4, 5, 6 ] ], dtype = np.bool_)
array_a

array([[ True,  True,  True],
       [ True,  True,  True]])

In [9]:
array_a = np.array([ [ 1, 2, 0 ], [ 4, 5, 6 ] ], dtype = np.bool_)
array_a

array([[ True,  True, False],
       [ True,  True,  True]])

In [11]:
array_a = np.array([ [ 1, 2, 3 ], [ 4, 5, 6 ] ], dtype = np.str_)
array_a

array([['1', '2', '3'],
       ['4', '5', '6']], dtype='<U1')