<a href="https://colab.research.google.com/github/Kavi-Sarna/365-python/blob/main/7%20-%20Data%20Preprocessing%20with%20NumPy/3%20-%20NumPy%20Fundamentals/5%20-%20NumPy%20Functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

### Universal Functions

https://numpy.org/devdocs/reference/ufuncs.html <- <i> A link to the documentation page on Universal Functions

In [2]:
array_a = np.array([ 1, 2, 3 ])
array_a

array([1, 2, 3])

In [3]:
array_b = np.array([ [1], [2] ])
array_b

array([[1],
       [2]])

In [4]:
matrix_c = np.array([ [ 1, 2, 3 ], [ 4, 5, 6 ] ])
matrix_c

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
np.add(array_a, matrix_c)

array([[2, 4, 6],
       [5, 7, 9]])

In [6]:
np.add(array_b, matrix_c)

array([[2, 3, 4],
       [6, 7, 8]])

In [7]:
np.add(array_b, matrix_c, dtype = np.float64)

array([[2., 3., 4.],
       [6., 7., 8.]])

In [8]:
np.add(array_b, matrix_c, dtype = np.str_)

UFuncTypeError: ignored

In [10]:
np.mean(matrix_c, axis = 0)

array([2.5, 3.5, 4.5])

In [11]:
matrix_c

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
np.mean(matrix_c, axis = 1)

array([2., 5.])