<a href="https://colab.research.google.com/github/Kavi-Sarna/365-python/blob/main/7%20-%20Data%20Preprocessing%20with%20NumPy/4%20-%20Working%20with%20Arrays/1%20-%20Basic%20Slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
matrix_A = np.array([ [ 1, 2, 3 ], [ 4, 5, 6 ] ])
matrix_A

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
matrix_A[:]

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
type(matrix_A[:])

numpy.ndarray

In [5]:
matrix_A[0:0]

array([], shape=(0, 3), dtype=int64)

In [6]:
matrix_A[0:1]

array([[1, 2, 3]])

In [7]:
matrix_A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
matrix_A[:, :]

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
type(matrix_A[:, :])

numpy.ndarray

In [10]:
matrix_A[:1]

array([[1, 2, 3]])

In [11]:
matrix_A[1:]

array([[4, 5, 6]])

In [12]:
matrix_A[2:]

array([], shape=(0, 3), dtype=int64)

In [13]:
matrix_A[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
matrix_A[0]

array([1, 2, 3])

In [15]:
matrix_A[:1]

array([[1, 2, 3]])

In [16]:
type(matrix_A[0])

numpy.ndarray

In [17]:
type(matrix_A[:1])

numpy.ndarray

In [18]:
matrix_A[0].shape

(3,)

In [19]:
matrix_A[:1].shape

(1, 3)

In [20]:
matrix_A[:-1]

array([[1, 2, 3]])

In [21]:
matrix_A[:, 1:]

array([[2, 3],
       [5, 6]])

In [22]:
matrix_A[1:, 1:]

array([[5, 6]])