<a href="https://colab.research.google.com/github/Kavi-Sarna/365-python/blob/main/7%20-%20Data%20Preprocessing%20with%20NumPy/4%20-%20Working%20with%20Arrays/2%20-%20Stepwise%20Slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
matrix_B = np.array([ [ 1, 1, 1, 2, 0 ], [ 3, 6, 6, 7, 4 ], [ 4, 5, 3, 8, 0 ] ])
matrix_B

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

In [3]:
matrix_B[:, :]

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

In [4]:
matrix_B[::, ::]

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

In [5]:
matrix_B[::2, ::]

array([[1, 1, 1, 2, 0],
       [4, 5, 3, 8, 0]])

In [6]:
matrix_B[::, ::2]

array([[1, 1, 0],
       [3, 6, 4],
       [4, 3, 0]])

In [7]:
matrix_B[::2, ::2]

array([[1, 1, 0],
       [4, 3, 0]])

In [8]:
matrix_B[::-2, ::2]

array([[4, 3, 0],
       [1, 1, 0]])

In [9]:
matrix_B[::-1, ::2]

array([[4, 3, 0],
       [3, 6, 4],
       [1, 1, 0]])

In [10]:
matrix_B[-1::-1, ::2]

array([[4, 3, 0],
       [3, 6, 4],
       [1, 1, 0]])