<a href="https://colab.research.google.com/github/Kavi-Sarna/365-python/blob/main/7%20-%20Data%20Preprocessing%20with%20NumPy/4%20-%20Working%20with%20Arrays/3%20-%20Conditional%20Slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
matrix_C = np.array([ [ 1, 1, 1, 2, 0 ], [ 3, 6, 6, 7, 4 ], [ 4, 5, 3, 8, 0 ] ])
matrix_C

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

In [3]:
matrix_C[:, 0]

array([1, 3, 4])

In [4]:
matrix_C[:, 0] > 2

array([False,  True,  True])

In [5]:
matrix_C[:, :] > 2

array([[False, False, False, False, False],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False]])

In [7]:
matrix_C[matrix_C[:, :] > 2]

array([3, 6, 6, 7, 4, 4, 5, 3, 8])

In [8]:
matrix_C[matrix_C[:, :] < 2]

array([1, 1, 1, 0, 0])

In [9]:
matrix_C[matrix_C[:, :] >= 2]

array([2, 3, 6, 6, 7, 4, 4, 5, 3, 8])

In [10]:
matrix_C[matrix_C[:, :] == 2]

array([2])

In [11]:
matrix_C[matrix_C[:, :] != 2]

array([1, 1, 1, 0, 3, 6, 6, 7, 4, 4, 5, 3, 8, 0])

In [12]:
matrix_C[matrix_C[:, :] % 2 == 0]

array([2, 0, 6, 6, 4, 4, 8, 0])

In [13]:
matrix_C[(matrix_C[:, :] % 2 == 0) & (matrix_C[:, :] <= 4)]

array([2, 0, 4, 4, 0])

In [14]:
matrix_C[(matrix_C[:, :] % 2 == 0) | (matrix_C[:, :] <= 4)]

array([1, 1, 1, 2, 0, 3, 6, 6, 4, 4, 3, 8, 0])