<a href="https://colab.research.google.com/github/Kavi-Sarna/365-python/blob/main/7%20-%20Data%20Preprocessing%20with%20NumPy/4%20-%20Working%20with%20Arrays/4%20-%20Dimensions%20and%20Squeeze%20Function.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
matrix_D = np.array([ [ 1, 1, 1, 2, 0 ], [ 3, 6, 6, 7, 4 ], [ 4, 5, 3, 8, 0 ] ])
matrix_D

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

In [3]:
matrix_D[0, 0]

1

In [4]:
type(matrix_D[0, 0])

numpy.int64

In [5]:
matrix_D[0, 0:1]

array([1])

In [6]:
type(matrix_D[0, 0:1])

numpy.ndarray

In [7]:
matrix_D[0:1, 0:1]

array([[1]])

In [8]:
type(matrix_D[0:1, 0:1])

numpy.ndarray

In [9]:
print(matrix_D[0, 0].shape)
print(matrix_D[0, 0:1].shape)
print(matrix_D[0:1, 0:1].shape)

()
(1,)
(1, 1)


In [10]:
matrix_D[0:1, 0:1].squeeze()

array(1)

In [11]:
type(matrix_D[0:1, 0:1].squeeze())

numpy.ndarray

In [12]:
matrix_D[0:1, 0:1].squeeze().shape

()

In [13]:
print(matrix_D[0:1, 0:1].squeeze())

1


In [15]:
np.squeeze(matrix_D[0:1, 0:1])

array(1)

In [16]:
print(matrix_D[0, 0].squeeze().shape)
print(matrix_D[0, 0:1].squeeze().shape)
print(matrix_D[0:1, 0:1].squeeze().shape)

()
()
()
